version: '3.1'

services:

  web:
    container_name: flask
    build: ./web
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./web:/usr/src/web
    depends_on:
      - db
#    entrypoint: ["python", "main.py"]

  db:
    container_name: postgres
    image: postgres:latest
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
#    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"